pipeline {
    agent any

    environment {
        DOCKER_IMAGE_NAME = 'notification-service'
        DOCKER_COMPOSE_FILE = 'docker-compose.yml'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'jenkins-github-config', url: 'https://github.com/rzabson/shop.git'
            }
        }
        stage('Build JAR') {
            steps {
                script {
                    // Build the JAR file using Maven
                    sh 'mvn -f notification-service/pom.xml clean package'
                    sh 'ls notification-service/target/'

                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    // Build the Docker image from the Dockerfile in the notification-service directory
                    sh 'docker build -t notification-service ./notification-service'
                }
            }
        }
        stage('Deploy with Docker Compose') {
            steps {
                script {
                    // Use Docker Compose to deploy the services
                    sh "cd notification-service && docker-compose -f ${DOCKER_COMPOSE_FILE} up  -d notification-service"
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed!'
        }
    }
}
