version: '3'
#wersja docker compose

services:
  my-jenkins:
    image: my-jenkins:buildx-latest
    container_name: jenkins
    restart: always
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /home/ubuntu/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Umożliwia Jenkinsowi komunikację z Dockerem na host'cie
  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: order-service
    ports:
        - "9005:9005"  # Adjust the port as needed
    entrypoint: [ "java", "-jar", "/app/order.jar" ]

  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: notification-service
    ports:
      - "9006:9006"  # Adjust the port as needed
    entrypoint: ["java", "-jar", "/app/notification.jar"]