version: '3'
services:
  my-jenkins:
    image: my-jenkins:buildx-latest
    container_name: jenkins
    restart: always
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /home/ubuntu/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Jenkins communication through host to docker
  order-service:
    image: order-service
    environment:
      - JAVA_APP_JAR=/deployments/application.jar
    volumes:
      - order-service/target/order-0.0.1-SNAPSHOT.jar:/deployments/application.jar
    ports:
        - "9005:9005"

  notification-service:
    image: notification-service
    environment:
      - JAVA_APP_JAR=/deployments/application.jar
    volumes:
      - notification-service/target/notification-0.0.1-SNAPSHOT.jar:/deployments/application.jar
    ports:
      - "9006:9006"
